---
title: "Visiting Scholars Schedule"
author: "Hargeisa Group Hospital and Taipei Municipal Wanfang Hospital"
format: 
  pdf:
    documentclass: article
    include-in-header:
      - text: |
          \usepackage[utf8]{inputenc}
          \usepackage{pgfgantt}
---


## Visiting Scholars Schedule to TMWH
\pagenumbering{gobble}

\begin{ganttchart}[vgrid,hgrid,progress label text={}, y unit chart=0.85cm]{1}{12}
    \gantttitle{2024}{12} \\ % Year 2024 with a total of 12 months

    \gantttitlelist{1,...,12}{1} \\ % Months from January to December
    
\ganttgroup{Batch 1}{5}{7} \\
\ganttmilestone{Dr. Chen, TMWH Pathologist TO HGH}{5} \\
    \ganttbar[progress=50]{Dr. Abdirahman (Hospital Director) MoU}{5}{5.5} \\
    \ganttbar[progress=50]{Dr. Khadar Good Nur (ICP Director)}{5}{5.5} \\
    \ganttbar[progress=100]{Dr. Saed Osman (Orthopedic)}{5}{7} \\
    \ganttbar[progress=100]{Dr. Mohamed Hassan Nur (Resident, Orthopedic)}{5}{8} \\
    \ganttbar[progress=100]{Dr. Hassan Mohamed Nur (Resident, Orthopedic)}{5}{10} \\

%

\ganttgroup{Batch 2}{7}{9} \\
\ganttmilestone{Dr. Chen, TMWH Orthopedic surgeon TO HGH}{7} \\
    \ganttbar[progress=100]{Dr. Saed Mohamed Osman (Resident, Orthopedic)}{7}{10} \\
    \ganttbar[progress=100]{Dr. Abdulrahman Adoosh Abdulaahi (Resident, Orthopedic)}{7}{10} \\
    \ganttbar[progress=100]{Dr. Ahmed Saeed (Orthopedic)}{7}{9} \\
    \ganttbar[progress=100]{Dr. Mustafe Ahmed Yusuf (Neurosurgery)}{7}{10} \\
    \ganttbar[progress=100]{Dr. Idris Hassan Dahir (Cardiologist)}{7}{9} \\


% Dr. Mustefe (Emergency), Miss Rakia (Ward nurse)

\ganttgroup{Batch 3}{9}{11} \\
\ganttmilestone{Dr. Wei, TMWH Neurosurgeon TO HGH}{9} \\
    \ganttbar[progress=100]{Dr. Yassin Awil (Orthopedic)}{9}{11} \\
    \ganttbar[progress=100]{Dr. Abdihamid Mohamed Ali  (Neurosurgery)}{9}{11} \\
    \ganttbar[progress=100]{Dr. Ahmed Hersi (NCD clinic)}{9}{11} \\
    \ganttbar[progress=100]{Mr. Ahmed (Nurse, OT director)}{9}{11} \\
    \ganttbar[progress=100]{Dr. Omer Mohamed Bihi (Pathology)}{9}{9} 

% *** no \\ at last line *** 
% Dr. Liban (ICU), Mr. Mustafe (Technician, Pathology)


\end{ganttchart}
