---
title: "Visiting Scholars Schedule"
author: "Hargeisa Group Hospital and Taipei Municipal Wanfang Hospital"
format: 
  pdf:
    documentclass: article
    include-in-header:
      - text: |
          \usepackage[utf8]{inputenc}
          \usepackage{pgfgantt}
---


## Visiting Scholars Schedule to TMWH
\pagenumbering{gobble}

\begin{ganttchart}[vgrid,hgrid,progress label text={}, y unit chart=0.85cm]{1}{12}
    \gantttitle{2024}{12} \\ % Year 2024 with a total of 12 months

    \gantttitlelist{1,...,12}{1} \\ % Months from January to December
    
% Dr. Chen, TMWH Pathologist TO HGH
% ***** 2025 Dr. Abdilahi Abdi (general surgery)
\ganttgroup{Batch 1}{6}{8} \\
%\ganttmilestone{}{6} \\
    \ganttbar[progress=100]{Dr. Nouh Ismail Mohamed (General Surgery)}{6}{8} \\
%    \ganttbar[progress=100]{Dr. Saed Osman (Orthopedic)}{6}{8} \\
    \ganttbar[progress=100]{Dr. Abdulrahman Adoosh Abdulaahi (Resident, Orthopedic)}{6}{8} \\
    \ganttbar[progress=100]{Dr. Hassan Mohamoud Nour (Resident, Orthopedic)}{6}{8} \\
    \ganttbar[progress=100]{Mr. Ahmed Hussein (Nurse, OT director)}{6}{8} \\

%

% Dr. Mustefe (Emergency), Miss Rakia (Ward nurse)
% Dr. Wei, TMWH Neurosurgeon TO HGH

\ganttgroup{Batch 2}{7}{9} \\
%\ganttmilestone{}{7} \\
%    \ganttbar[progress=100]{Dr. Yassin Awil (Orthopedic)}{7}{9} \\
    \ganttbar[progress=100]{Dr. Abdihamid Mohamed Ali  (Neurosurgery)}{7}{9} \\
    \ganttbar[progress=100]{Dr. Adnan Sayid Abdo (General Surgery)}{7}{9} \\
    \ganttbar[progress=100]{Dr. Omer Mohamed Bihi (Pathology)}{7}{9} \\ % HPV DNA
    \ganttbar[progress=100]{Dr. Idris Hassan Dahir (Cardiologist)}{7}{9} \\  % CCU, ICU

%
% Dr. Chen, TMWH Orthopedic surgeon TO HGH

\ganttgroup{Batch 3}{9}{11} \\
%\ganttmilestone{}{9} \\
    \ganttbar[progress=100]{Dr. Saed Mohamed Osman (Resident, Orthopedic)}{9}{11} \\
    \ganttbar[progress=100]{Dr. Mohamed Hassan Nur (Resident, Orthopedic)}{9}{11} \\
%    \ganttbar[progress=100]{Dr. Ahmed Saeed (Orthopedic)}{9}{11} \\
    \ganttbar[progress=100]{Dr. Mustafe Ahmed Yusuf (Neurosurgery)}{9}{11} \\ 
    \ganttbar[progress=100]{Mr. Mustafe (Technician, Pathology)}{9}{11} 



% *** no \\ at last line *** 
% Dr. Liban (ICU), Mr. Mustafe (Technician, Pathology)
% Dr. Ahmed Hersi (NCD clinic)
%
% December: conference for Dr. Abdirahman (Hospital Director) MoU
% bye bye: Dr. Khadar Good Nur (IPC Director)

\end{ganttchart}
